# Generated by Django 5.1.6 on 2025-02-18 11:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_consumer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Provider',
            new_name='Seller',
        ),
    ]
