# Generated by Django 5.1.6 on 2025-02-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_alter_consumer_user_alter_seller_user_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-02-18 12:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consumer',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='consumer',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='consumer',
            name='type',
            field=models.CharField(choices=[('buisness', 'Buisness'), ('customer', 'Customer')], default='Customer', max_length=20),
        ),
        migrations.AddField(
            model_name='consumer',
            name='working_hours',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-02-18 12:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='type',
            field=models.CharField(choices=[('buisness', 'Buisness'), ('customer', 'Customer')], default='Customer', max_length=20),
        ),
        migrations.AddField(
            model_name='seller',
            name='working_hours',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
