# Generated by Django 5.1.6 on 2025-02-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0009_alter_consumer_type_alter_seller_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='type',
            field=models.CharField(choices=[('Buisness', 'buisness'), ('Customer', 'customer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='seller',
            name='type',
            field=models.CharField(choices=[('Buisness', 'buisness'), ('Customer', 'customer')], max_length=20),
        ),
    ]
