# Generated by Django 5.1.6 on 2025-02-18 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0011_testmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
