# Generated by Django 5.1.6 on 2025-02-18 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0013_alter_consumer_type_alter_seller_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumer',
            name='type',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='type',
        ),
    ]
