# Generated by Django 5.1.6 on 2025-02-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0014_remove_consumer_type_remove_seller_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='type',
            field=models.CharField(choices=[('buisness', 'Buisness'), ('customer', 'Customer')], default='Customer', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='type',
            field=models.CharField(choices=[('buisness', 'Buisness'), ('customer', 'Customer')], default='Customer', max_length=20),
            preserve_default=False,
        ),
    ]
