# Generated by Django 5.1.6 on 2025-02-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0016_alter_consumer_type_alter_seller_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='profile',
            field=models.FileField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='seller',
            name='profile',
            field=models.FileField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
