# Generated by Django 5.1.6 on 2025-02-19 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0017_consumer_profile_seller_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumer',
            old_name='profile',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='profile',
            new_name='file',
        ),
    ]
