# Generated by Django 5.1.6 on 2025-02-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0018_rename_profile_consumer_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='description',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='location',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='working_hours',
        ),
        migrations.AlterField(
            model_name='consumer',
            name='description',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='working_hours',
            field=models.CharField(default='', max_length=255),
        ),
    ]
