# Generated by Django 5.1.6 on 2025-02-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0020_consumer_tel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumer',
            name='description',
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='location',
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='tel',
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='working_hours',
        ),
        migrations.AddField(
            model_name='seller',
            name='description',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='seller',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='seller',
            name='working_hours',
            field=models.CharField(default='', max_length=255),
        ),
    ]
