# Generated by Django 5.1.6 on 2025-02-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0021_remove_consumer_description_remove_consumer_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='tel',
            field=models.CharField(default='', max_length=255),
        ),
    ]
