# Generated by Django 5.1.6 on 2025-02-20 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_app', '0002_offerdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerdetail',
            name='offer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='offer_app.offer'),
            preserve_default=False,
        ),
    ]
