# Generated by Django 5.1.6 on 2025-02-20 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_app', '0004_offerdetail_features'),
        ('user_auth', '0022_seller_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='user_auth.seller'),
            preserve_default=False,
        ),
    ]
