# Generated by Django 5.1.6 on 2025-02-20 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer_app', '0006_alter_offer_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='user',
            new_name='user_details',
        ),
    ]
