# Generated by Django 5.1.6 on 2025-02-20 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer_app', '0007_rename_user_offer_user_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='user_details',
            new_name='user',
        ),
    ]
