# Generated by Django 5.1.6 on 2025-03-13 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer_app', '0008_rename_user_details_offer_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
