# Generated by Django 5.1.6 on 2025-03-07 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0002_order_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='offer',
        ),
    ]
