# Generated by Django 5.1.6 on 2025-03-07 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0005_order_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='offer',
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
