# Generated by Django 5.1.6 on 2025-03-07 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_app', '0008_rename_user_details_offer_user'),
        ('order_app', '0006_remove_order_offer_delete_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='offer_detail',
            field=models.ForeignKey(default=70, on_delete=django.db.models.deletion.CASCADE, related_name='offer_detail', to='offer_app.offerdetail'),
            preserve_default=False,
        ),
    ]
