# Generated by Django 5.1.6 on 2025-03-07 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0008_remove_order_name_order_created_at_order_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
