# Generated by Django 5.1.6 on 2025-03-18 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_app', '0005_alter_review_business_user_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
